---
title: "Statisztika 2."
subtitle: "1. előadás: Ismétlés"
author: "Morauszki András"
format: 
  revealjs:
    theme: league
    transition: slide
editor: visual
---

## A félév felépítése

- 12 alkalom, 90 perc/alkalom
- témák:
  - Hipotézisvizsgálat: két változó közötti asszociáció
  - Modellépítés: regressziós modellek alapjai
- számonkérés: írásbeli (nyitott könyv) vizsga
- kommunikáció: morauszki.andras\@gmail.com

## Módszerek

- Függetlenségvizsgálat (kereszttábla): alacsony mérési szintű változók közötti asszociáció
- Korrelációszámítás: magas mérési szintű változók közötti asszociáció
- Lineáris regresszió: modellezés és előrejelzés
- Egyszempontos varianciaelemzés: csoportátlagok modellalapú összevetése

## Előkövetelmények

- Alapvető algebra: képletek megértése és használata
- Ábrák és táblázatok olvasása
- Valószínűségelmélet alapjai: valószínűség, feltételes valószínűség, valószínűségi változók
- Eloszlások: sűrűségfüggvény, eloszlásfüggvény
- Statisztika alapjai: leíró és induktív statisztika
  - Leíró statisztikák
  - Intervallumbecslés
  - Hipotézisvizsgálat

## Célkitűzések

- Kutatási kérdés "lefordítása" ellenőrizhető hipotézisekre
- Megfelelő módszer kiválasztása és elvégzése
- Módszer feltételei teljesülésének a felmérése
- A próba/modell eredményeinek értelmezése
- Mi következik és mi nem az eredményekből
  - Együttjárás és okság megkülönböztetése
  - (Nem) szignifikáns eredmények jelentése, szignifikancia vs. erősség
- Eredmények közlése másokkal

# Ismétlés

## Általános

- populáció/minta
- megfigyelés/kísérlet
- elemzési/megfigyelési egység
- paraméter/statisztika
- változók, típusaik, mérési szintek
- független (magyarázó) és függő változók

## Központi kérdés

"A mintában megfigyelt mintázatok mire engednek következtetni egy szélesebb populációra vonatkozóan?"

Cél:

- megalapozott állítások
- minta alapján
- szélesebb populációra vonatkozóan

## Alaphelyzet

- mintában megfigyelhető különbség/összefüggés
- kérdés: adódhat-e ez a véletlen mintavétel jellegéből, vagy általánosítható a populációra?
- miért merül fel egyáltalán ez a kérdés?

## Bizonytalanság

- egy másik mintából más értékeket kapnánk

- további kérdések:

  - milyen jellegű az összefüggés?
  - mennyire erős az összefüggés?
  - oksági kapcsolatról van szó vagy csak együttjárásról?
  - szerepet játszhatnak egyéb tényezők is?

- a statisztika segítségével számszerűsíthető a kapcsolat és a bizonytalanság is

## Hipotézisvizsgálat

- nullhipotézis, ellenhipotézis
- szignifikanciaszint
- tesztstatisztika
- nulleloszlás
- p érték
- döntés, első- és másodfajú hiba
- próba ereje, hatásnagyság

## Példa

Kutatási kérdés:

"Különbözik-e, hogy mennyi időt fordítanak sportolásra a nők és a férfiak?"

## Hipotézisek

Mi lesz a nullhipotézis?

Mi lesz az ellenhipotézis?

## Hipotézisek

$$H_0: \mu_1 = \mu_2 \\
H_1: \mu_1 \neq \mu_2$$

- $\mu$ és nem $\overline{x}$

- lehetne \< vagy \> is (egyoldali próba)

- Hogyan fogalmaznák ezt meg "emberi nyelven"?

## Szignifikanciaszint

Mit jelent, hogy 5%-os szignifikanciaszint mellett döntünk?

## Szignifikancia-érték

Számszerűsíteni tudjuk, mennyi a valószínűsége, hogy igaz nullhipotézis (egyenlőség) esetén mennyi a valószínűsége, hogy az adott mintának megfelelő eltérést lássunk a várt értéktől (jelen esetben 0-tól)

Hogyan tesszük ezt?

## Különbség kiszámítása

Tegyük fel, hogy kiszámítjuk a különbséget a mintában, és ez alapján a férfiak valamennyivel (pl. 15 perc) többet sportolnak hetente.

Mi következik ebből?

## Tesztstatisztika

Pl. Független mintás t-próba esetén

$$t = \frac{\overline{x_1}-\overline{x_2}}{s_k*\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}$$

## Tesztstatisztika eloszlása

A tesztstatisztikának igaz nullhipotézis esetén ismert az eloszlása (=**nulleloszlás**).

t-próba esetén: [Interaktív vizualizáció](https://statisticsfundamentals.com/visual-tools/t-distribution-visualizer/)

Ez így rendben, de nekünk csak egy mintánk van... Mihez kezdünk vele?

## p-érték

A p-érték kifejezi, hogy a mi mintánk mennyire *kompatibilis* a nullhipotézissel.

A p-érték azt számszerűsíti, hogy mennyi a valószínűsége **igaz nullhipotézis esetén**, hogy egy mintából **ilyen, vagy ennél jelentősebb** különbséget (vagy hatást) figyeljünk meg.

Pl. megkapjuk, hogy p = 0,03

Milyen következtetést vonhatunk le?

## Mit jelent és mit nem a szignifikáns próba?

Erős az összefüggés a két változó között?

Sikerült bizonyítani, hogy a nullhipotézis nem igaz?

Hibázhattunk?

## Első- és másodfajú hiba

A nullhipotézis lehet igaz és hamis.

A döntésünk lehet az, hogy elvetjük, vagy az, hogy nem sikerül elvetni.

Kétféle hibát követhetünk el:

- elvethetünk igaz nullhipotézist
- nem vetünk el hamis nullhipotézist

## Első- és másodfajú hiba

A nullhipotézis lehet igaz és hamis.

A döntésünk lehet az, hogy elvetjük, vagy az, hogy nem sikerül elvetni.

Kétféle hibát követhetünk el:

- elvethetünk igaz nullhipotézist → elsőfajú hiba
- nem vetünk el hamis nullhipotézist → másodfajú hiba

## Próba ereje

Annak a valószínűsége, hogy *adott nagyságú eltérést* kimutatunk egy bizonyos nagyságú mintából, meghatározott szignifikanciaszint mellett.

A másodfajú hiba = 1 - próba ereje

[Interaktív vizualizáció](https://rpsychologist.com/d3/nhst/)

## Kontakt

### Honlap

Még a szemináriumhoz készült, és mérsékelten naprakész, de legalább van: [Itt](https://morauszkia.github.io/stat2sz)

### E-mail

[morauszki.andras\@gmail.com](mailto:morauszki.andras@gmail.com)
